//! `vaultlocal` Core Library
//!
//! This crate provides the foundational logic for the VaultLocal secret management CLI.
//! 
//! # Modules
//! - `crypto`: Implements secure wrappers over Argon2, HKDF, and AES-GCM-SIV.
//! - `secure_mem`: Constructs tailored specific memory zeroing policies.
//! - `db`: Manages SQLite database provisioning, SQLite schema creation, and actual operations over Vault entries.
//! - `error`: Aggregates errors generated by underlying I/O and crypto layers.
//! - `util`: Helpful encoding and decoding utility methods for parsing input.

pub mod crypto {
    pub mod constants;
    pub mod kdf;
    pub mod cipher;
}

pub mod secure_mem {
    pub mod types;
}

pub mod db {
    pub mod connection;
    pub mod schema;
    pub mod vault;
    pub mod meta;
    pub mod header;
}

pub mod error;

pub mod util {
    pub mod encoding;
}

pub use db::vault::Vault;
pub use error::VaultError;

#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use super::*;
}